name: Testing Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Markdown
        uses: avto-dev/markdown-lint@v1
        with:
          args: "docs/**/*.md"

  run-tests:
    runs-on: windows-latest
    needs: lint-docs
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
  
      - name: Install dependencies
        working-directory: tests
        run: npm install
  
      - name: Run Jest tests
        working-directory: tests
        run: npx jest --watchAll=false

