name: Playwright Tests (with Mock API)
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install frontend dependencies
      run: npm ci
      working-directory: client

    - name: Start frontend server
      run: nohup npm start &
      working-directory: client

    - name: Install Jest dependencies
      run: npm ci
      working-directory: tests/jest

    - name: Start mock API server
      run: nohup node start-mock-server.js &
      working-directory: tests/jest

    - name: Wait for frontend to be ready
      run: |
        for i in {1..30}; do
          nc -z localhost 3000 && echo "Frontend is up!" && exit 0
          sleep 1
        done
        echo "Frontend did not start in time" && exit 1
      shell: bash

    - name: Wait for mock API to be ready
      run: |
        for i in {1..30}; do
          nc -z localhost 3001 && echo "Mock API is up!" && exit 0
          sleep 1
        done
        echo "Mock API did not start in time" && exit 1
      shell: bash

    - name: Install Playwright dependencies
      run: npm ci
      working-directory: tests/playwright

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: tests/playwright

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: tests/playwright

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: tests/playwright/playwright-report/
        retention-days: 30
