name: Playwright Tests (with Mock API)
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 22


    - name: Install global wait-on
      run: npm install -g wait-on

    - name: Install frontend dependencies
      run: npm ci
      working-directory: client

    - name: Install Jest dependencies
      run: npm ci
      working-directory: tests/jest

    - name: Install Playwright dependencies
      run: npm ci
      working-directory: tests/playwright

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: tests/playwright

    - name: Start frontend server
      run: npm start &
      working-directory: client

    - name: Start mock API server
      run: node start-mock-server.js &
      working-directory: tests/jest

    - name: Wait for servers to be ready
      run: wait-on http://localhost:3000 http://localhost:3001

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: tests/playwright

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: tests/playwright/playwright-report/
        retention-days: 30
